image:
  registry: 10.43.114.154:5000
  tag: dev

hostname: flow-dev.turdblossom.dev

existingSecret: flow-dev-secrets

# louise has had intermittent network/reboot issues; tina has been stable.
nodeSelector:
  kubernetes.io/hostname: tina
