authentik:
  existingSecret:
    secretName: authentik-secret-key

postgresql:
  enabled: true
  auth:
    username: authentik
    database: authentik
    existingSecret: authentik-secret-key
    secretKeys:
      userPasswordKey: AUTHENTIK_POSTGRESQL__PASSWORD

server:
  ingress:
    enabled: false
