apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zot
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://zotregistry.dev/helm-charts
      chart: zot
      targetRevision: "0.1.122"
      helm:
        valueFiles:
          - $values/apps/zot/values.yaml
    - repoURL: git@github.com:angloyna/homelab-gitops.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: zot
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
