service:
  type: ClusterIP
  port: 5000

# louise has had intermittent network/reboot flakiness; pin to the
# control-plane node instead since it's been stable.
nodeSelector:
  kubernetes.io/hostname: tina

persistence: true
pvc:
  create: true
  accessModes: ["ReadWriteOnce"]
  storage: 20Gi

mountConfig: true
configFiles:
  config.json: |-
    {
      "storage": { "rootDirectory": "/var/lib/registry" },
      "http": {
        "address": "0.0.0.0",
        "port": "5000"
      },
      "log": { "level": "info" },
      "extensions": {
        "search": { "enable": true, "cve": { "updateInterval": "24h" } },
        "ui": { "enable": true }
      }
    }
